import React from 'react';

import Layout from '../layouts/layout';

export default function Help () {
    return (
      <Layout>
        <div className="ml-4 pl-4 mr-4 pr-4 mb-4 pb-4">
          <h3 className="orange-color mb-4 pb-2">Help</h3>

          <p className="paragraph-font mt-2">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Est velit egestas dui id ornare arcu odio ut. Imperdiet nulla malesuada pellentesque elit eget gravida. Massa sapien faucibus et molestie. Scelerisque felis imperdiet proin fermentum leo vel orci porta. Et tortor consequat id porta nibh venenatis cras sed. Ut tristique et egestas quis ipsum. Quam elementum pulvinar etiam non quam lacus. Nec feugiat nisl pretium fusce. Faucibus ornare suspendisse sed nisi lacus sed viverra tellus in. Donec pretium vulputate sapien nec sagittis. Facilisis mauris sit amet massa vitae tortor condimentum. Phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor aliquam. Vitae sapien pellentesque habitant morbi tristique senectus. Libero id faucibus nisl tincidunt. Ipsum faucibus vitae aliquet nec ullamcorper sit amet. Cras pulvinar mattis nunc sed.</p>

          <p className="paragraph-font mt-2">Lorem ipsum dolor sit amet consectetur adipiscing elit duis tristique. Non consectetur a erat nam at lectus urna duis convallis. Egestas maecenas pharetra convallis posuere morbi leo urna. Vivamus at augue eget arcu dictum. At augue eget arcu dictum varius duis at consectetur lorem. Lorem ipsum dolor sit amet. Dui sapien eget mi proin. Nec ultrices dui sapien eget mi proin sed. Ut tristique et egestas quis. Eros donec ac odio tempor orci dapibus ultrices. Diam maecenas sed enim ut sem viverra. Nisl nisi scelerisque eu ultrices vitae auctor eu augue ut. Donec ultrices tincidunt arcu non sodales neque. Ut diam quam nulla porttitor. Risus nullam eget felis eget. Amet aliquam id diam maecenas ultricies mi. Nunc congue nisi vitae suscipit.</p>

          <p className="paragraph-font mt-2">Sagittis id consectetur purus ut faucibus. Ut consequat semper viverra nam. Odio facilisis mauris sit amet massa vitae. Id ornare arcu odio ut sem nulla pharetra diam sit. Congue nisi vitae suscipit tellus mauris a diam. Velit dignissim sodales ut eu sem integer vitae justo eget. Tincidunt ornare massa eget egestas. Vulputate enim nulla aliquet porttitor lacus luctus. Feugiat pretium nibh ipsum consequat nisl vel pretium lectus quam. Erat imperdiet sed euismod nisi porta lorem mollis. Vulputate odio ut enim blandit volutpat maecenas volutpat blandit. Tincidunt eget nullam non nisi est sit amet facilisis. Adipiscing elit pellentesque habitant morbi. Eget gravida cum sociis natoque penatibus et magnis dis parturient. Risus nec feugiat in fermentum posuere. Purus in massa tempor nec feugiat nisl. Platea dictumst vestibulum rhoncus est. Vitae turpis massa sed elementum tempus egestas sed. Vitae tempus quam pellentesque nec nam aliquam sem. Aenean euismod elementum nisi quis eleifend quam.</p>

          <p className="paragraph-font mt-2">Iaculis nunc sed augue lacus viverra. Gravida quis blandit turpis cursus. Ac turpis egestas maecenas pharetra convallis posuere. Bibendum est ultricies integer quis auctor elit. Tristique nulla aliquet enim tortor at auctor urna nunc. Lacus suspendisse faucibus interdum posuere lorem. Id faucibus nisl tincidunt eget nullam non nisi. Auctor neque vitae tempus quam pellentesque nec nam aliquam sem. Nulla malesuada pellentesque elit eget. Proin sagittis nisl rhoncus mattis rhoncus urna. Purus sit amet volutpat consequat mauris nunc. Dictum at tempor commodo ullamcorper a lacus vestibulum sed arcu. Volutpat lacus laoreet non curabitur gravida arcu ac. Urna cursus eget nunc scelerisque viverra. Massa vitae tortor condimentum lacinia quis. Libero enim sed faucibus turpis in eu mi. Velit ut tortor pretium viverra suspendisse potenti nullam.</p>
        </div>
      </Layout>
    );
}